import "./globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppProviders } from "./providers";
import { Footer, Header } from "../components";
import { siteConfig } from "@/config/site";
// import { fontSans } from "@/config/fonts";
// import { Providers } from "./providers";
// import { Navbar } from "@/components/navbar";
// import { Link } from "@nextui-org/link";
import clsx from "clsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: siteConfig.name,
    template: `%s - ${siteConfig.name}`,
  },
  description: "Generated by create next app",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon-16x16.png",
    apple: "/apple-touch-icon.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={clsx("flex flex-col grow-1", inter.className)}>
        <AppProviders themeProps={{ attribute: "class", defaultTheme: "dark" }}>
          <Header />
          <main className="site-main">{children}</main>
          <Footer />
        </AppProviders>
      </body>
    </html>
  );
}
